### ISSUE TITLE
dependency for running train_depth.py ?

### ISSUE THREAD

**Issue by icoz69** [EPFL-VILAB/omnidata-paper-code-dump#4]
Hi,
thanks for the amazing work. i am interested in the MIDAS training part, what's are the required packages for running this script?

**Comment by icoz69** [comment]
also, i try to use train_depth.py by running
python train_depth.py --config_file config/depth.yml --experiment_name rgb2depth --val_check_interval 3000 --limit_val_batches 100 --max_epochs 10
as instructed by https://docs.omnidata.vision/training.html
it seems the command does not work. for example, there is no argument named  --config_file

**Comment by Ainaz99** [comment]
Hi @icoz69! Thanks for your question.
I'm guessing that you are using the training script in the paper code dump repo. You should use the [omnidata-tools repo](https://github.com/EPFL-VILAB/omnidata-tools/tree/main/omnidata_tools/torch) for Midas training code. Package requirements are also listed [here](https://github.com/EPFL-VILAB/omnidata-tools/blob/main/omnidata_tools/torch/requirements.txt). Let me know if you had any other questions.

**Comment by icoz69** [comment]
Hi, thanks for the quick reply!  I will try it after downloading the dataset.
