### ISSUE TITLE
which 5 datasets are used for training depth models?

### ISSUE THREAD

**Issue by icoz69** [EPFL-VILAB/omnidata-paper-code-dump#6]
hi, it is said the 5-dataset portion (about 400M imags) is used for depth training, but I could not find which 5 datasets are used. Could you specify?  I have downloaded replica, replica+gos, hypersim, hm3d, and blended_MVG.

**Comment by Ainaz99** [comment]
Hi @icoz69 ,

The version of our depth models which is reported in the paper is trained on Taskonomy, Replica, Replica+GSO, Blended_MVG, and Hypersim.

**Comment by icoz69** [comment]
thanks for the reply!
